inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"

Layout/HashAlignment:
  EnforcedColonStyle: key
  EnforcedHashRocketStyle:  key

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space

Metrics/AbcSize:
  Enabled: true
  Max: 45
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Max: 100
  Exclude:
    - "*.gemspec"
    - "Rakefile"
    - "spec/**/*"

Metrics/ClassLength:
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  Max: 30
  Exclude:
    - "test/**/*"

Metrics/ParameterLists:
  Max: 5

Naming/MemoizedInstanceVariableName:
  Enabled: true

Naming/VariableNumber:
  Enabled: true

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/ClassAndModuleChildren:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: true

Style/EmptyMethod:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/NumericPredicate:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrivialAccessors:
  AllowPredicates: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Layout/MultilineArrayBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Layout/MultilineHashBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: same_line

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/LineLength:
  Enabled: true
  Max: 250

Style/FormatStringToken:
  Enabled: true
  EnforcedStyle: template

RSpec/MessageSpies:
  Enabled: true
  EnforcedStyle: receive

RSpec/FilePath:
  Enabled: true
  SpecSuffixOnly: true