version: "2"
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jamesbond
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
