version: 2
jobs:
  build:
    working_directory: ~/circleci-pg-online-schema-change
  
    docker:
      - image: ruby:3.0.0
        environment:
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_USER: jamesbond
  
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: jamesbond
          POSTGRES_DB: postgres

    steps:
      - checkout
 
      # Restore bundle cache
      - restore_cache:
          keys:
            - pg-online-schema-change-{{ checksum "Gemfile.lock" }}
            - pg-online-schema-change-
 
      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - run: apt-get update
      - run: apt-get install -y sudo
      - run: sudo apt install -y postgresql-client

      # Store bundle cache
      - save_cache:
          key: pg-online-schema-change-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
 
      - run:
          name: lint
          command: bundle exec rubocop

      - run:
          name: Parallel RSpec
          command: bundle exec rspec
 
      # Save artifacts
      - store_test_results:
          path: /tmp/test-results