name: CI
on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9.6.2-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: jamesbond
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install dependent libraries
        run: sudo apt install -y postgresql-client

      - name: Gem cache
        id: cache-bundle
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}

      - name: Bundle install
        env:
          RAILS_ENV: test
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle

      - name: Run Lint
        run: bundle exec rubocop

      - name: Run RSpec
        run: bundle exec rspec
        env:
          POSTGRES_USER: jamesbond
          POSTGRES_DB: postgres