name: Smoke Test PG 9.6
on: [push]

concurrency:
  group: branch-smoke-9-6-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pgbench-rspec:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "2.7.7"
          - "3.0.5"
          - "3.1.3"
          - "3.2.1"
    services:
      postgres:
        image: postgres:9.6.2-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: jamesbond
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 10s --health-retries 20
    steps:
      - uses: actions/checkout@v1

      - name: Install dependent libraries
        run: sudo apt install -y postgresql-client

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Bundle install
        env:
          RAILS_ENV: test
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle

      - name: Run pgbench and rspec
        run: bundle exec rspec spec/lib/smoke_spec.rb
        env:
          POSTGRES_USER: jamesbond
          POSTGRES_DB: postgres
